volumes:
  bundle:
    driver: local

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: uaI7m2kmWd949DMv4dCh

  web:
    environment:
      PGPASSWORD: uaI7m2kmWd949DMv4dCh
    build: .
    platform: linux/arm64
    entrypoint: [ setup/entry ]
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/refugetravesties
      - /refugetravesties/node_modules
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
